### ISSUE TITLE
Navigator error

### ISSUE THREAD

**Issue by MartinSher** [arkon/ng-sidebar#63]
Hi

I get the error below when I try include ng-sidebar in the VS2017 project using the sample SPA application as per https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/.

This is after adding ng-sidebar in my project.json.

How do I get past the error?

Thanks
Martin

Exception: Call to Node module failed with error: ReferenceError: navigator is not defined
at Sidebar._isIOS (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\main-server.js:587:40)
at new Sidebar (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\main-server.js:156:18)
at new Wrapper_Sidebar (/SidebarModule/Sidebar/wrapper.ngfactory.js:7:18)
at CompiledTemplate.proxyViewClass.View_AppComponent0.createInternal (/AppModule/AppComponent/component.ngfactory.js:28:23)
at CompiledTemplate.proxyViewClass.AppView.create (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:11951:25)
at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:15:19)
at CompiledTemplate.proxyViewClass.AppView.createHostView (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:11964:25)
at ComponentFactory.create (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:7361:29)
at ApplicationRef_.bootstrap (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:8330:61)
at D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:8166:93
at Array.forEach (native)
at PlatformRef_._moduleDoBootstrap (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:8166:46)
at D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:8118:31
at ZoneDelegate.module.exports.ZoneDelegate.invoke (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:74198:26)
at Object.onInvoke (D:\Developments\Zenith.Angular2.Portal\Zenith.Web\ClientApp\dist\vendor.js:4053:41)

**Comment by arkon** [comment]
Are you doing server side rendering? This module doesn't currently support that.

**Comment by MartinSher** [comment]
To be honest, not sure as I am very much still learning how to get a angular 2 app running in VS2017 using .net Core.

**Comment by arkon** [comment]
A quick Google search leads me to believe that it _is_ doing server side rendering. You could try deactivating it: http://stackoverflow.com/a/40258105
